SELECT 
    R.REST_ID, 
    R.REST_NAME, 
    R.FOOD_TYPE, 
    R.FAVORITES, 
    R.ADDRESS, 
    ROUND(AVG(V.REVIEW_SCORE), 2) AS SCORE
FROM 
    REST_INFO AS R
JOIN 
    REST_REVIEW AS V 
    ON R.REST_ID = V.REST_ID
WHERE 
    R.ADDRESS LIKE '서울%'
GROUP BY 
    R.REST_ID
ORDER BY 
    SCORE desc, R.FAVORITES desc;