-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
From FIRST_HALF
LEFT Join ICECREAM_INFO on ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
Where ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' and FIRST_HALF.TOTAL_ORDER > 3000;
# order By FIRST_HALF.TOTAL_ORDER asc;